### ISSUE TITLE
Transcription Plugin

### ISSUE THREAD

**Issue by stevespaw** [lutangar/lutangar#2]
I'm sorry if this is not the best way to communicate. We are having issues with the plug in and don't know where to turn.
When we first installed it, it seemed to work on some 3-5 minute videos then we tried a longer one and it no longer works on any clip.

How to we start to diagnose this. In a new instance it stated to do a 30 second clip and there are some details in the worker3 log, but it seemed to stop after the first 10 seconds or so.

Is this being supported in any way?

Thanks for any help
Steve
Steve at Shadow-Technologies dot com

**Comment by lutangar** [comment]
Thx for reaching out, I understand why you posted here, however we're now transferring the repository to a more accessible __Gitlab__ instance, see [peertube-plugin-transcription](https://gitlab.com/apps_education/peertube/plugin-transcription).

Could you please post your issue there instead?
